"""Core PropertyHunter domain models."""

from datetime import UTC, datetime
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, HttpUrl, field_validator


class UtilityStatus(StrEnum):
    """Traffic-light status for utility availability."""

    GREEN = "green"
    YELLOW = "yellow"
    RED = "red"
    UNKNOWN = "unknown"


class SyncStatus(StrEnum):
    """External synchronization state for an analyzed property."""

    NOT_SYNCED = "not_synced"
    SYNCED = "synced"
    FAILED = "failed"


class CapturedListing(BaseModel):
    """Listing payload captured from a marketplace page.

    Parameters
    ----------
    source_site:
        Marketplace hostname or logical source name.
    url:
        Canonical URL of the listing page.
    title:
        Human-readable listing title.
    raw_text:
        Visible listing text captured from the page.
    raw_html:
        Optional raw HTML snapshot for future extraction improvements.
    captured_at:
        Timestamp when the browser userscript captured the listing.
    """

    model_config = ConfigDict(str_strip_whitespace=True)

    source_site: str = Field(min_length=1)
    url: HttpUrl
    title: str = Field(min_length=1)
    raw_text: str = Field(min_length=1)
    raw_html: str | None = None
    captured_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class ExtractedProperty(BaseModel):
    """Structured property facts extracted from listing text.

    Parameters
    ----------
    price:
        Total asking price in PLN when known.
    price_per_sqm:
        Asking price per square meter in PLN when known.
    area_sqm:
        Parcel or usable area in square meters when known.
    parcel_id:
        Polish cadastral parcel identifier if present in the listing.
    city:
        City, village, or municipality mentioned in the listing.
    street:
        Street or local address fragment when available.
    regulatory_text_summary:
        Short extraction summary of planning or zoning text.
    """

    price: float | None = Field(default=None, ge=0)
    price_per_sqm: float | None = Field(default=None, ge=0)
    area_sqm: float | None = Field(default=None, ge=0)
    parcel_id: str | None = None
    city: str | None = None
    street: str | None = None
    regulatory_text_summary: str | None = None

    @field_validator("parcel_id", "city", "street", "regulatory_text_summary")
    @classmethod
    def empty_string_to_none(cls, value: str | None) -> str | None:
        """Normalize optional text fields."""
        if value is None:
            return None
        stripped = value.strip()
        return stripped or None


class ParcelGeometry(BaseModel):
    """Parcel geometry resolved from cadastral services.

    Parameters
    ----------
    parcel_id:
        Polish cadastral parcel identifier.
    centroid_2180:
        Centroid coordinates in EPSG:2180 as ``(x, y)`` meters.
    centroid_wgs84:
        Centroid coordinates in WGS84 as ``(latitude, longitude)``.
    wkt:
        Parcel geometry encoded as WKT.
    """

    parcel_id: str
    centroid_2180: tuple[float, float]
    centroid_wgs84: tuple[float, float]
    wkt: str


class UtilityAssessment(BaseModel):
    """Nearest known utility network assessment.

    Parameters
    ----------
    network_type:
        Utility network name, for example water, sewage, electricity, or gas.
    status:
        Distance-based traffic-light status.
    distance_meters:
        Nearest known network distance in meters, if measured.
    source_layer:
        Source service or layer name that produced the result.
    """

    network_type: str
    status: UtilityStatus
    distance_meters: float | None = Field(default=None, ge=0)
    source_layer: str | None = None


class RegulatorySummary(BaseModel):
    """Structured planning and regulatory summary."""

    summary: str
    mpzp_status: str | None = None
    risks: list[str] = Field(default_factory=list)


class ExternalLinks(BaseModel):
    """Useful external links derived from parcel and coordinate data."""

    google_maps: HttpUrl | None = None
    geoportal: HttpUrl | None = None
    uldk: HttpUrl | None = None


class AnalyzedProperty(BaseModel):
    """Complete analysis result stored by PropertyHunter.

    Parameters
    ----------
    id:
        Stable local identifier generated by the repository or use case.
    listing:
        Captured source listing payload.
    extracted:
        Structured listing facts extracted by an agent.
    geometry:
        Optional cadastral geometry resolved through ULDK.
    utilities:
        Utility availability assessments.
    regulatory_summary:
        Planning and zoning summary.
    external_links:
        Derived map and cadastral links.
    sync_status:
        Notion synchronization state.
    notion_page_id:
        Stored page id for idempotent Notion updates.
    created_at:
        Local creation timestamp.
    """

    id: str
    listing: CapturedListing
    extracted: ExtractedProperty
    geometry: ParcelGeometry | None = None
    utilities: list[UtilityAssessment] = Field(default_factory=list)
    regulatory_summary: RegulatorySummary | None = None
    external_links: ExternalLinks = Field(default_factory=ExternalLinks)
    sync_status: SyncStatus = SyncStatus.NOT_SYNCED
    notion_page_id: str | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
